version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./dev/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: cicd
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
